# Generated by Django 4.0.1 on 2022-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='issues',
            field=models.ManyToManyField(related_name='countries', to='issues_environment.Issue'),
        ),
    ]
