# Generated by Django 4.0.1 on 2022-02-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_environment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='issue',
            new_name='issues',
        ),
    ]
