# Generated by Django 4.0.2 on 2022-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_environment', '0002_alter_country_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
